STATION_NAMES = [
    "15_16th_and_locust",
    "12_13th_and_locust",
    "9_10th_and_locust",
    "8th_and_market",
    "city_hall",
    "broadway",
    "ferry_ave",
    "collingswood",
    "westmont",
    "haddonfield",
    "woodcrest",
    "ashland",
    "lindenwold",
]
